spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: m1,m2
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.24:4980/shardingsphere_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
        username: alc607wjyd
        password: jwabc'/;ASD12
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.24:4980/shardingsphere_test_1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
        username: alc607wjyd
        password: jwabc'/;ASD12
    sharding:
      #广播表
      broadcast-tables: t_udict
      tables:
        t_order:
          actual-data-nodes: m1.t_order_$->{1..2}
          key-generator:
                  column: id
                  type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_order_$->{id % 2 + 1}
        t_udict:
          key-generator:
            column: id
            type: SNOWFLAKE

    props:
      sql:
        show: true

mybatis:
   mapper-locations: classpath:mapper/*.xml
